# Daily Challenge 40

Create a function that transposes a 2D matrix.

Examples

transpose_matrix([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]) ➞ [ [1, 2, 3], [1, 2, 3], [1, 2, 3] ]

transpose_matrix([ [5, 5], [6, 7], [9, 1] ]) ➞ [ [5, 6, 9], [5, 7, 1] ]

In [7]:
def transpose_matrix(matrix):
    result = []
    for x in range(len(matrix[0])):
        row = []
        for y in range(len(matrix)):
            row.append(matrix[y][x])
        result.append(row)
    return result

import numpy as np
def transpose_matrix2(matrix):
    return np.array(matrix).transpose()

In [8]:
print(transpose_matrix([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]))
print(transpose_matrix([ [5, 5], [6, 7], [9, 1] ]))

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[[5, 6, 9], [5, 7, 1]]


In [9]:
print(transpose_matrix2([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]))
print(transpose_matrix2([ [5, 5], [6, 7], [9, 1] ]))

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[5 6 9]
 [5 7 1]]
